### ISSUE TITLE
Maintainer permissions?

### ISSUE THREAD

**Issue by mgasner** [conda-forge/dagster-feedstock#9]
Hi there, I'm just reaching out per the comments at https://github.com/dagster-io/dagster/issues/413#issuecomment-558473198 to ask for maintainer permissions on this.

**Comment by bollwyvl** [comment]
Cool!

You can propose yourself with a PR to this repo that adds your gh handle to
#/extras/maintainers, and one of us will merge. Not presently at a device
with access to gh, but would love to have you on board!

Last chance I had, was slogging through the open pr to do all of the builds
at once, which takes >30 minutes, but otherwise it's 20 prs, which must be
merged in a specific order, which sounds like a pain, even if highly
automated. So long as you guys are always going to do synced releases, it
may be an effective trade.

Maybe if we get that (or some other) approach working, once, we can go to a
single, arch-specific build for the core, another for all the noarch stuff,
and maybe a special one for aws, because it's proving to be tough due to
win/py38 issues.
